In [1]:
from keras.models import Sequential
from keras.utils import np_utils
from keras.layers import Dense, Dropout, Activation, Flatten, Conv1D, pooling
from keras.layers.convolutional import Convolution1D, MaxPooling1D
from keras.callbacks import EarlyStopping
import pandas as pd, numpy as np
from sklearn.preprocessing import RobustScaler
import random
from numpy import *

np.random.seed(30)

test1=pd.read_csv('newnor.csv', header=None)
test2=pd.read_csv('scared.csv', header=None)

#test1=pd.read_csv('normal4.csv')
#test2=pd.read_csv('emer4.csv')

#test1 = test1.drop(["Time", "Unnamed: 0"], axis=1)
#test2 = test2.drop(["Time", "Unnamed: 0"], axis=1)
test1.drop(test1.columns[[0]], axis='columns')
test2.drop(test1.columns[[0]], axis='columns')


#test1.head()
#test2.head()

Using TensorFlow backend.

           1       2       3       4      5      6      7   8   9
0     140724   21203   55254   11081  61490  30174   3422  41  37
1      36312   22356   50954   12044  27715  42938  10503  41  37
2     269186     660   64161   23124  66893   2623   3336  41  37
3     166279   31959   56911    6629  56671  18987   5328  41  37
4      88440   15967  170572   31234  29704  40604   7563  41  37
..       ...     ...     ...     ...    ...    ...    ...  ..  ..
794  1558471  518566   59457   80400  70079  34062   9853  57  30
795    85148   11894    3861    6504   1773   1135    543  64  35
796   381961  184438   22013  234464  56903  30069  16078  66  43
797   220923  111009   18090   24549  18702   4953   3927  56  37
798    54791   15748   11682    5070   8585   1264    577  57  51

[799 rows x 9 columns]

In [2]:
test1["label"] = "unsafe"
test2["label"] = "safe"

X=pd.concat([test1, test2])

#print(X.shape)
#print(X)
#"""
#Y를 범주형 데이터로 전환
bclass = {'safe':[1, 0], 'unsafe':[0, 1]}
y = np.empty((len(X), 2))
for i, v in enumerate(X['label']):
    y[i] = bclass[v]

#X축의 label을 제외한 테스트 데이터 셋
del X['label']
#X = X[['delta','theta','lowAlpha','highAlpha','lowBeta','highBeta','lowGamma','midGamma']].to_numpy()
X=X.to_numpy()
X.shape
#"""

(5679, 10)

In [3]:
tmp = [[x,y_tmp] for x, y_tmp in zip(X, y)]
random.shuffle(tmp)
X= [n[0] for n in tmp]
y = [n[1] for n in tmp]

X = np.asarray(X, dtype=np.float32)
y = np.asarray(y, dtype=np.float32)

#print(X.shape, y.shape)

In [4]:
#scaler = RobustScaler()
#scaler.fit(X)
#X = scaler.transform(X)
#print(X)
#np.mean(X), np.std(X)

In [5]:
x_train, y_train = X[1:900], y[1:900]
x_test, y_test = X[900:], y[900:]

In [6]:
x_train = x_train.reshape(x_train.shape[0], 10, 1)
x_test = x_test.reshape(x_test.shape[0], 10, 1)

print('x_train shape:', x_train.shape[1])
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')
print(y_train.shape[1])

x_train shape: 10
899 train samples
4779 test samples
2

In [7]:
def evaluate_model(x_train, y_train, x_test, y_test):
    model = Sequential()
    verbose, epochs, batch_size = 0, 10, 32
    n_timesteps, n_features, n_outputs = x_train.shape[1], x_train.shape[2], y_train.shape[1]
    model.add(Convolution1D(filters=64, kernel_size=3, activation='relu',
                        input_shape=(n_timesteps,n_features)))
    model.add(Convolution1D(filters=64, kernel_size = 3, activation='relu'))
    model.add(Dropout(0.25))
    model.add(MaxPooling1D(pool_size = 2))
    model.add(Flatten())
    model.add(Dense(100, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(n_outputs, activation='softmax'))

    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    hist=model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, verbose=verbose)
    print(hist.history['loss'])

    _, accuracy= model.evaluate(x_test, y_test, batch_size=batch_size, verbose=0)
    return accuracy

In [8]:
repeats=10
scores = list()
for r in range(repeats):
	score = evaluate_model(x_train, y_train, x_test, y_test)
	score = score * 100.0
	print('>#%d: %.3f' % (r+1, score))
	scores.append(score)
    
# summarize results
print(scores)
m, s = mean(scores), std(scores)
print('Accuracy: %.3f%% (+/-%.3f)' % (m, s))

[6609.073007280224, 1337.1005602742196, 714.6577479751808, 265.47438926824077, 209.63287969608928, 167.57858211975608, 169.16379771269735, 130.73838448365353, 92.35347406644047, 82.15800216386262]
>#1: 91.944
[5939.517179461554, 949.7877448467046, 510.9583551493847, 388.6974885015188, 295.4690362338362, 205.38168382485532, 165.32977649234692, 127.72851559105386, 126.5721591317216, 65.53686000666974]
>#2: 93.409
[4258.844690715378, 1256.6065737646863, 737.9365682124561, 362.85350150340656, 324.78217228262525, 224.66068313225225, 195.92207541799917, 125.41625318856075, 82.9687803851118, 102.5650658485489]
>#3: 92.028
[2058.370262884325, 1013.5889345366379, 417.9167209578568, 283.0417036453264, 146.9621112080119, 124.57949019486169, 125.03332587423526, 87.49452019586447, 89.20984807932072, 68.24809173482146]
>#4: 94.162
[3684.8801288541085, 788.4691948301933, 489.0290716084278, 357.80708978332586, 203.3121757804353, 174.43666711452937, 168.26701311964348, 112.42468933427958, 50.68312182442365, 83.7847427096595]
>#5: 93.618
[2597.734442620707, 932.0580239980186, 520.2864163306451, 367.00894677625746, 241.74550278168235, 119.76767039060327, 235.8103787746525, 227.59136127815628, 88.7118059101041, 82.83279239879434]
>#6: 93.953
[3608.5752181243047, 1120.1823733184442, 757.4820549851397, 399.86452439152225, 273.00194816886386, 252.04121030610185, 162.74374025576105, 161.81261748758385, 186.34874110068046, 127.34725997657479]
>#7: 93.346
[3976.888114888888, 1307.9330506796832, 923.7117376783666, 579.1938598768597, 317.2703193435414, 277.53999038373803, 146.01918813940947, 152.5057757317158, 156.38502346713497, 61.872366119147145]
>#8: 92.802
[4153.155981689724, 1371.4156769783267, 826.2545364261072, 626.8007354906059, 311.4163262478104, 230.6283373228037, 244.11576848353639, 108.65270402036334, 121.25529702327673, 115.9093392004028]
>#9: 93.764
[4947.024339109427, 1452.3838702616622, 1006.5789076621594, 756.2425159628319, 411.64651845692265, 351.11476870187795, 243.66813206487026, 178.83020637350964, 130.755694186346, 110.19589954753872]
>#10: 94.497
[91.94391965866089, 93.40866208076477, 92.02762246131897, 94.16195750236511, 93.61791014671326, 93.95270943641663, 93.34588646888733, 92.80183911323547, 93.76438856124878, 94.49675679206848]
Accuracy: 93.352% (+/-0.813)

NameError: name 'model' is not defined